### ISSUE TITLE
Visual fixes

### ISSUE THREAD

**Issue by mihneaz** [Tradeshift/elements#102]
The components we migrate from UI Components to Elements have to be visually indistinguishable from the originals. Therefore I made a list with small details that were lost in the migration:

Buttons: 
- [x] Font-weight should be 600. Currently too thin.
- [x] There should not be a border at hover
- [x] Border width is incorrect for the focused state (should be thicker)

File card: 
- [x] Card contents flicker (change position) at hover
- [x] Height of the card should be 60px

Input
- [x] Input states are different from UI Components (borders are incorrect for hover and focused)

**Comment by esmailpour-hosein** [comment]
Where did you check them? @mihneaz

**Comment by mihneaz** [comment]
> Where did you check them? @mihneaz
https://tradeshift.github.io/elements
