### ISSUE TITLE
Note in elements

### ISSUE THREAD

**Issue by lloydhumphreys** [Tradeshift/elements#107]
Essentially copy over the existing note:

- [x] Standard state without icon
- [x] Standard state with icon
- [x] Ada state with icon
- [x] Neutral state without icon
- [x] Neutral state with icon
- [x] Dismissable note (x)

Some new considerations:
- [ ] Loading state - spinner as an icon when neutral-note means "Background process executing" for example
- [x] Button, or links within the note?
- [x] RTL support

@mihneaz to provide designs
- [ ] Check yellow for accurate contrast

**Comment by mihneaz** [comment]
Here are the neutral states:
![Specs](https://user-images.githubusercontent.com/510261/61793650-e1fa3080-ae1f-11e9-8450-d31298d5f022.png)

Abstract link: https://share.goabstract.com/3f3f4c9e-bdc6-4a1b-9825-489191ccfacf?mode=design&sha=34900ed0449059b6d1ed7ca10813831e4e3b4026

**Comment by esmailpour-hosein** [comment]
@mihneaz Thanks! 🙏 
In this design you didn't add border radius for the top part, but in `ts-ui` it has the `border-radius: 3px`. What should I do?
