### ISSUE TITLE
Components needed =)

### ISSUE THREAD

**Issue by CarloAl** [Tradeshift/elements#163]
Hello guys,

for the development of Link we would need these components in the immediate future:
 

- a header (lvl 1 and 2) - I am currently using TS UI but it is incompatible with ts-aside so I would need to get away from it.
- a modal (like in TS UI)
- dialog (low priority..)

Not sure if anything that you see here is up to become a component or if this is custom dev
![image](https://user-images.githubusercontent.com/5701042/65698269-88f78480-e07c-11e9-9ec3-ea7727f49f86.png)

Could you guys give me a rough ETA on this? I would like to understand if I should wait for it or do some custom implementation because unfortunately we have deadlines as well. 

Thanks!

**Comment by esmailpour-hosein** [comment]
At least I can say that we can't do it in this sprint. I'll update you if I have some news.
