### ISSUE TITLE
File uploader design review

### ISSUE THREAD

**Issue by DocGroth** [Tradeshift/elements#18]

**Comment by mihneaz** [comment]
![Review](https://user-images.githubusercontent.com/510261/56641411-9e9ff280-6675-11e9-836b-47e62f55bab1.png)

**Comment by mihneaz** [comment]
Also, here are the latest specs:
![New-Specs](https://user-images.githubusercontent.com/510261/56659921-8ee8d400-669e-11e9-8b7b-eeeb4472efa8.png)
* If drag and drop is out of scope, please ignore that section

**Comment by mihneaz** [comment]
Here are some specs for long file names edge case, right to left support and even some size suggestions.
![New-Specs](https://user-images.githubusercontent.com/510261/56727404-e9426d00-6750-11e9-8d90-7f36ec3bbb14.png)

If you'd like to inspect those with Abstract, here's a direct link to the artboard: https://share.goabstract.com/1cff6ebb-e41a-467c-a379-17f65ebd3559
