### ISSUE TITLE
Components from `elements` don't support translations

### ISSUE THREAD

**Issue by MirelaPaun** [Tradeshift/elements#193]
Components from `elements` don't support translations

For example, the attachments component doesn't support translated labels, `Select` and `Select file` aren't translated.
A fix could be that attachments component to receive these strings already translated from the app where are used, like it is for the text under the `Select file` input. The helper text is provided from PRv2 app already translated.

![image](https://user-images.githubusercontent.com/28289435/69244060-f3c0ca00-0bac-11ea-942c-8c3d489fe33a.png)

**Comment by esmailpour-hosein** [comment]
Thanks for reporting. We have it and you can pass the translated the text into slots.
I'll create a PR to update all components readme with all the available props, events and slots, soon.

Here's how it works: 
```
<ts-file-uploader-input accepted-file-extensions='["doc", "pdf", "jpg"]'>
	<span slot="placeholder-text">Changed placeholder text</span>
	<span slot="button-text">Changed button text</span>
	<span slot="drop-text">Changed drop text</span>
</ts-file-uploader-input>
```

**Comment by MirelaPaun** [comment]
Thanks for this fix. I already implemented it in PRv2 for the attachment components.
