### ISSUE TITLE
Hover on .error-message in file-card shows 'undefined' tooltip in Chrome

### ISSUE THREAD

**Issue by tshadrinatradeshift** [Tradeshift/elements#195]
Hover on .error-message in `file-card` shows `undefined` tooltip

Chrome Version 60.0.3112.78 
in FireFox v 70.0.1 - OK

![file-card-undefined-tooltip](https://user-images.githubusercontent.com/17042951/69321988-a577fd80-0c76-11ea-962d-3bc72caed800.png)

**Comment by esmailpour-hosein** [comment]
We are not supporting that version of chrome, thanks for reporting 🙏 
https://support.tradeshift.com/knowledgebase/article/206369444

**Comment by esmailpour-hosein** [comment]
For future reader, The reason for this bug was an issue with slotchange event.
