### ISSUE TITLE
Checkbox without label renders incorrectly

### ISSUE THREAD

**Issue by aleks-elkin** [Tradeshift/elements#275]
With label:
<img width="481" alt="checkbox with label" src="https://user-images.githubusercontent.com/55530374/80966673-3bfb3e00-8e15-11ea-974d-1c11903d7214.png">

Without label:
<img width="496" alt="checkbox without label" src="https://user-images.githubusercontent.com/55530374/80966687-44537900-8e15-11ea-84a3-fa806b19ebc1.png">

Checkbox should keep block size without text in label.

**Comment by esmailpour-hosein** [comment]
Do you know any use-cases for no label? I think it can lead to misuse and hacky solution, which will cause inconsistency.

**Comment by aleks-elkin** [comment]
> Do you know any use-cases for no label? I think it can lead to misuse and hacky solution, which will cause inconsistency.

Yes, we already have such case in a list of companies in Network Manager.
